Fix missing-prototypes
weather-parsers.c:192:1: error: no previous prototype for 'parse_moonposition' [-Werror=missing-prototypes]

Signed-off-by: Olaf Hering <olaf@aepfle.de>